### ISSUE TITLE
要是能将如何搭建写出来就好了qwq

### ISSUE THREAD

**Issue by misaka10843** [Eigh18n/Leize_bot#1]
因为我在centos8服务器中搭建失败了很多次hoshino机器人
所以超想能有一个相对简单容易的搭建教程（兔兔机器人也是几次都搭建失败了qwq）
如果作者闲麻烦的话也可以关闭此Issues qwq

**Comment by Eigh18n** [comment]
我搞这个仓库只是为了在服务器能直接pull …(:ｪ)|￣|_
前端是用的gocqhttp教程走的
等我放假有空再写具体的教程吧
鸽了.jpg
